#%RAML 1.0 NamedExample

value:
  -
    name: Mario cars
    released: 2019-09-01
    platforms:
      -
        xbox one
      -
        playstation
    genres:
      -
        Racing
      -
        Adventure
    stores:
      -
        playstation store
      -
        xbox store
    rating: 4.8
    top_rating:
      id: 5
      title: Excellent
      count: 200
      percent: 96.5
  -
    name: Cars
    released: 2020-09-01
    platforms:
      -
        xbox one
      -
        playstation
    genres:
      -
        Racing
      -
        Adventure
    stores:
      -
        playstation store
      -
        xbox store
    rating: 4.6
    top_rating:
      id: 4
      title: Recommended
      count: 200
      percent: 96.5