#%RAML 1.0 NamedExample
  
value:
  -
    name: myGame
    released: 2019-09-01
    platforms:
      -
        xbox one
      -
        playstation
    genres:
      -
        Racing
      -
        Adventure
    stores:
      -
        playstation store
      -
        xbox store
    rating: 4.96
  -
    name: Cars
    released: 2020-09-01
    platforms:
      -
        xbox one
      -
        playstation
    genres:
      -
        Racing
      -
        Adventure
    stores:
      -
        playstation store
      -
        xbox store
    rating: 4.85
