#%RAML 1.0
title: video-games-process-api

types:
  Game: !include data-types/gameType.raml

# *********** RAWG.IO ***********

/games-rawg:
  get:
    description: get games from rawg api
    queryParameters:
      key: string
      dates?: date-only
      platforms?: array
      genres?: array
      stores?: array
    responses:
      200:
        body:
          application/json:
            type: Game[]
            example: !include examples/gamesExample.raml


# *********** MONGODB ***********

/search-games:
  get:
    description: search games from mongoDB with filters
    queryParameters:
      dates?: date-only
      platforms?: array
      genres?: array
      stores?: array
    responses:
      200:
        body:
          application/json:
            type: Game[]
            example: !include examples/gamesExample.raml

/post-games:
  post:
    description: Post games to mongoDB
    body:
      application/json:
        type: Game[]
    responses:
      201:
        body:
          application/json:
            example: 
              { 
                "message": "Your games had been properly saved to mongoDB",
                "Total Records": 250
              }

/rating-games:
  get:
    description: get games from mongoDB ordered by rating ASC or DSC
    queryParameters:
      rating: number
    responses:
      200:
        body:
          application/json:
            type: Game[]
            example: !include examples/gamesExample.raml










